### ISSUE TITLE
update video listings on briefings.html 

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#362] opened 2017-01-13 18:14 UTC
Use the same style as http://commons.openshift.org/videos.html to list (in LIFO) the 10 most recent briefings and SIG videos from youtube channel in the bottom half of the briefings.html page and remove the out-of-date older list of videos

@wgordon17

**Comment by wgordon17** [comment] 2017-01-13 18:24
Duplicate of issue #361

**Closed by wgordon17** 2017-01-13 18:24 UTC
